# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            AUV IIT Kharagpur's Blog
tagline:          'Autonomous Underwater Vehicle Research Group'
description:      'We are an undergraduate student group working in the field of autonomous underwater robotics, designing submarines for international competitions.'
baseurl:          https://auviitkgp.github.io/blog/
baseurl-notrailingslash: https://auviitkgp.github.io/blog

author:
  name:           'Siddharth Kannan'
  url:            https://github.com/icyflame

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/auviitkgp/kraken_3.0
