# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            AUV
tagline:          'Autonomous Underwater Vehicle Research Group'
description:      'We are an undergraduate student group working in the field of autonomous underwater robotics, designing submarines for international competitions.'
url:              http://auv-iitkgp.in/blog
baseurl:          /

author:
  name:           'Siddharth Kannan'
  url:            https://github.com/icyflame

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/auviitkgp/kraken_3.0
